//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrpBnd
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DrpBindEntities : DbContext
    {
        public DrpBindEntities()
            : base("name=DrpBindEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Districtt_Tbl> Districtt_Tbl { get; set; }
        public virtual DbSet<State_Tbl> State_Tbl { get; set; }
        public virtual DbSet<Stud_Tbl> Stud_Tbl { get; set; }
    
        public virtual ObjectResult<sp_District_Result> sp_District(Nullable<int> stid)
        {
            var stidParameter = stid.HasValue ?
                new ObjectParameter("stid", stid) :
                new ObjectParameter("stid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_District_Result>("sp_District", stidParameter);
        }
    
        public virtual int sp_Insert(Nullable<int> stid, Nullable<int> dsid, string na, Nullable<int> ag, string ad)
        {
            var stidParameter = stid.HasValue ?
                new ObjectParameter("stid", stid) :
                new ObjectParameter("stid", typeof(int));
    
            var dsidParameter = dsid.HasValue ?
                new ObjectParameter("dsid", dsid) :
                new ObjectParameter("dsid", typeof(int));
    
            var naParameter = na != null ?
                new ObjectParameter("na", na) :
                new ObjectParameter("na", typeof(string));
    
            var agParameter = ag.HasValue ?
                new ObjectParameter("ag", ag) :
                new ObjectParameter("ag", typeof(int));
    
            var adParameter = ad != null ?
                new ObjectParameter("ad", ad) :
                new ObjectParameter("ad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert", stidParameter, dsidParameter, naParameter, agParameter, adParameter);
        }
    
        public virtual ObjectResult<sp_State_Result> sp_State()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_State_Result>("sp_State");
        }
    }
}
